### ISSUE TITLE
FSL Script Issue

### ISSUE THREAD

**Issue by djrotenberg** [CAMH-Scientific-Computing/SCC#1]
Address FSL Issue:

SCC User in Imaging Section is reporting an issue with an FSL/Batch submission script:

"In doing this I also found that the script I was using (which loops through a series of directories) was launching the feat command before the one in the previous loop had terminated (which is why I had so many processes running on the management node last week), I worked around this by inserting a sleep, but I have no idea why that was the case. I made up some test files and now it seems that I can run the script and it works, I can also submit it to the job queue but it I do that is doesn’t run. If someone could look into this that would be great!!"

The scripts can be found here:

Job submission script:
/imaging/scratch/Hendershot/chendershto/data/analysis/cihr_infusion/scripts/analysis_scripts/batch_test.sh

Script to launch FEAT:
/imaging/scratch/Hendershot/chendershto/data/analysis/cihr_infusion/scripts/analysis_scripts/feat_test.sh

**Comment by pipitone** [comment]
This is not an FSL issue. The `feat_test.sh` command is basically this: 

``` sh
cmd="feat $subjectdir/1081/20130314/ATTN/ATTN1/design.fsf &"
eval $cmd
```

The trailing ampersand (`&`) on the `cmd` is causing the command to run in the background. If you were to be running several of these scripts on a node or in a loop, each command would fork off into the background immediately and not wait until the command terminated (that is what the `&` does). 

I'll have to see your full script to understand more about what you are trying to do and where you are running into trouble, but hopefully this helps you get started.

**Comment by djrotenberg** [comment]
Thanks very much for taking the time to review this script! This question was posed by one of our users in the imaging section and this is a huge help! 

If it's alright I'll pass your comment back to the user and CC you. Please feel free to follow up if you like.

**Comment by pipitone** [comment]
Certainly. Or ask the user to reply here.
