### ISSUE TITLE
Load Average Spking 

### ISSUE THREAD

**Issue by djrotenberg** [CAMH-Scientific-Computing/SCC#10]
The load average on mgmt2 spikes with no clear cause. This must be diagnosed ASAP as it causes serious interruptions to service.

**Comment by pipitone** [comment]
Sent this in an email to you, but just so it stays top of mind: 

Some thoughts from looking at `/var/log/messages`:
- The root partition is 97% full (is now below 80%).
- node01's domain name and PBS configuration need fixing
- unknown usb0 network device.
- samba (`nmbd`) is complaining. why? 
- `abrt` is saving core dumps in /var/spool. a) move to a different partition? b) what is failing?  
- `pulseaudio` is complaining. 
- `mgmt`1 nfs server not responding messages occur often... why?
- there's a kernel oops/stacktrace in the logs for khugepage, which I  don't fully understand, but could be something to look at (e.g. [this](https://bugzilla.redhat.com/show_bug.cgi?id=879801))

**Comment by pipitone** [comment]
Also, @djrotenberg noticed that a bind mount over top of an NFS mount was leading to I/O hangs on that mount which then drives up the load average. This has since been fixed.

**Comment by djrotenberg** [comment]
Major updates to system configuration, and node functions has currently limited the load average. Furthermore a cronjob launching "du" on mounts with erroneous filesystems was likely the cause. The new file systems and disabling of the du cronjob should have resolved this as well.
