### ISSUE TITLE
Explore setting harder user limits on login/management nodes

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#11]
Separate from load average spiking (#10) is the related issue of users doing long running processing on the management node. As much as users are told not to do this, apparently they don't comply. Doing this sort of work on the management/login node leads to problems for everyone. 

So, along with more education around how to play nicely on the management node, we could set more restrictive limits on cpu/memory usage for users. 

For reference, here is what scinet has set in their`/etc/security/limits.conf` files:

``` sh
# login node
$ cat /etc/security/limits.conf 
*     -    nofile    20000
*     -    memlock   unlimited
*     -    as        4194304
*     -    rss       524288
*     -    cpu       5
*     -    nproc     256
#*     -    maxlogins 60

# development node
$ cat /etc/security/limits.conf                                                                                 
*       hard    nofile  20000
*       soft    nofile  20000
*       hard    memlock unlimited
*       soft    memlock unlimited
#*       hard    as      4194304
#*       soft    as      4194304
*       hard    rss     4194304
*       soft    rss     4194304
*       hard    cpu     30 
*       soft    cpu     15
```

I think the development node limits look pretty good. :-)

**Comment by djrotenberg** [comment]
Excellent. I've used a balance between the two considering that the management node still functions as both to some degree.

**Comment by pipitone** [comment]
Okay. I was playing around with this this morning -- perhaps you saw my settings commented out -- and I was noticing some trouble with logging in when I had certain limits set. Hadn't figured out if what I was seeing was related to limits or SCC filesystem trouble we've been seeing or what. Hence commenting out my settings. 

In any case, let's just keep an eye on this as we get the system back online.

**Comment by djrotenberg** [comment]
Thanks Jon! Limits imposed on management 2 and less restrictive limits placed on the two development nodes. These can and should be revisited over time.
