### ISSUE TITLE
Explore disabling user cron capability on the management node 

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#12]
To avoid things like `du -hs /verylarge-filesystem` every fifteen minutes.

**Comment by qchang** [comment]
"sudo touch /etc/cron.allow" should do the trick. Make sure that /etc/cron.allow is empty and remove /etc/cron.deny.

**Comment by andycamh** [comment]
add in crontab
*/5 \* \* \* \* killall du   >/dev/null 2>&1
*/5 \* \* \* \* killall df   >/dev/null 2>&1
