### ISSUE TITLE
Enable PBS email notifications on job completion

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#14]
There is a change request in the IMG queue around opening ports for email access, I'm told. Perhaps once that is done we can turn this feature on, or at least provide an option for users to get email notifications if they want them.

**Comment by pipitone** [comment]
See also #17

**Comment by djrotenberg** [comment]
We have successfully enabled these ports through the SCC firewall, so this should be possible now. Andy please revisit.

**Comment by andycamh** [comment]
Already finished set up email gateway.
User can get their email notify when define 
#PBS -M mailaddr
#PBS -m abe
