### ISSUE TITLE
Node15 appears to run particularly slow for PET reconstruction

### ISSUE THREAD

**Issue by djrotenberg** [CAMH-Scientific-Computing/SCC#18]
Although the process appears to be consuming the appropriate resources the job is has taken longer than any of the other jobs in the set. It is not clear whether this is specifically related to node15.

**Comment by pipitone** [comment]
Wait, what was the resolution?

**Comment by djrotenberg** [comment]
This was not related to the SCC, but a bug that Peter identified in his code.
