### ISSUE TITLE
CPU limits on mgmt2 are interrupting file transfers from SciNet

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#21]
After implementing CPU limits (see #11) we now face the problem that long rsync's from Scinet's datamover node can timeout. 

I've temporarily disabled the CPU limits on mgmt2 to allow a user to complete a data transfer. 

Solutions: 
- Remove CPU limits on mgmt2 for good
- Open sftp-only access to mgmt1 from datamover1 and remove limits (mgmt1 is now the ftp transfer node anyway).

**Comment by djrotenberg** [comment]
I agree with the second option in which sftp-only access is provided for management 1. I have submitted a change request to CompuCom and will reference the Ticket number here as soon as it is returned. 

I would not recommend removing the CPU limits if we can avoid it. Let's keep an eye on the transfer in question and try to reinstate the limits as soon as possible.

**Comment by djrotenberg** [comment]
The CPU limits have been reinstated given the transfer completion.

**Comment by djrotenberg** [comment]
Removing the CPU limit, or reducing it did not take effect even after log out and log in. I was however able to increase the CPU time limit and have it take effect. 
-          hard    cpu          60
-          soft    cpu          60

[spai@mgmt2 root]$ ulimit -a
cpu time               (seconds, -t) 3600
