### ISSUE TITLE
Install/Configure RStudio (dev01,dev02)

### ISSUE THREAD

**Issue by djrotenberg** [CAMH-Scientific-Computing/SCC#23]

**Comment by pipitone** [comment]
Perhaps you've seen it, but there's this tutorial for how to install rstudio on centos 6: 
https://biolives.wordpress.com/2013/07/09/installing-rstudio-an-advanced-gui-for-r-on-centos-6/

**Comment by andycamh** [comment]
according to pipitone's doc, rstudio is installed on dev01 and dev02,
user can run it with:
1. module load RSTUDIO/v0.97.551
2. rstudio
