### ISSUE TITLE
SSH fails from dev01/02 to other nodes

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#26]
From a dev node: 

``` sh
[jpipitone@dev01 ~]$ ssh node10                                                       
ssh: /quarantine/Libs/lib64/libcrypto.so.10: no version information available (required by ssh)
ssh: /quarantine/Libs/lib64/libcrypto.so.10: no version information available (required by ssh)
ssh: /quarantine/Libs/lib64/libcrypto.so.10: no version information available (required by ssh)
ssh: relocation error: ssh: symbol EC_GROUP_cmp, version OPENSSL_1.0.1_EC not defined in file libcrypto.so.10 with link time reference
```

**Comment by djrotenberg** [comment]
Although the messages are ugly for sure, this was done for the purpose of preventing access to nodes other than dev01 and dev02. However, there must be better ways!

**Comment by pipitone** [comment]
Yeah, should be doable with an appropriate Match block/AllowUsers in `/etc/sshd_config`

Also/alternatively, might be worth adding a message saying access is
restricted in order to cut down on the complaints. 

I guess ultimately, the issue with sshing is that we don't want users
shelling into nodes and running stuff directly. We could ask SciNet how
they configure their nodes since they seem to restrict ssh access to
nodes where your jobs are running, and when the job ends, all user
processes are killed. That's nice.

**Comment by pipitone** [comment]
Or, via changes to the routing table. :-D

**Comment by djrotenberg** [comment]
Agreed. I've written a short inquiry to the SciNet folks to see if they have any suggestions.

**Comment by djrotenberg** [comment]
I've found a simple program as part of the 'pbstools' package called 'reaver' that has found usage on several academic clusters. It simply checks whether the user has a job in the queue, if not other processes are killed. This therefore allows standard job submission, interactive jobs, but not ad-hoc processes on the compute nodes.

I have tested with a few simple cases, (i.e. running reaver manually after job submission and separate user login) and have distributed this program to all compute nodes. It now needs to be entered into the crontab, however a few more tests would be good.

**Comment by pipitone** [comment]
Beautiful! This sounds like a great solution.

**Comment by djrotenberg** [comment]
'reaver' has been tested and implemented in crontab to kill all processes run by users who are not running jobs on the same node. Note, however that this includes the 'ganglia' user, so a modification to the script to prevent this would be ideal.

**Comment by pipitone** [comment]
Oh that's annoying. Not sure if this is the same script: 
https://github.com/Norky/PBS-tools/blob/master/sbin/reaver

but on line 31 there is a "safelist" of users that shouldn't be killed.
Perhaps add ganglia to that?

**Comment by djrotenberg** [comment]
Excellent. This is the same script, so I will revise this ASAP.

**Comment by andycamh** [comment]
already add ganglia to reaver safelist , gmod should be ok!
