### ISSUE TITLE
MODULEPATH has the quarantine listed 3 times on login node

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#27]
On the login node, the MODULEPATH environment variable (which the `module` command uses) has the quarantine path listed 3 times: 

``` sh
[jpipitone@login ~]$ echo $MODULEPATH
:/quarantine/Modules/Modules/3.2.9/modulefiles/:/quarantine/Modules/Modules/3.2.9/quarantine/:/quarantine/Modules/Modules/3.2.9/modulefiles/:/quarantine/Modules/Modules/3.2.9/quarantine/:/quarantine/Modules/Modules/3.2.9/modulefiles/:/quarantine/Modules/Modules/3.2.9/quarantine/
```

I think this has to do with extras in `/etc/profile.d` but I haven't looked into it. 

The upshot is that running `module avail` gives lots of redundant output, but since the quarantine shouldn't be used on the login node, perhaps the fix for this is just to disable `module` entirely.

**Comment by djrotenberg** [comment]
Down to 2!

**Comment by djrotenberg** [comment]
Now only one series is displayed on management and compute nodes.
