### ISSUE TITLE
No manual pages for qsub on dev01/02

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#29]
`qsub` works (obviously) but the man pages are only available on the login node.

**Comment by djrotenberg** [comment]
[root@dev02 ~]# yum install man-pages
Loaded plugins: fastestmirror
Setting up Install Process
Determining fastest mirrors
- base: centos.bhs.mirrors.ovh.net
- extras: centos.bhs.mirrors.ovh.net
- updates: centos.bhs.mirrors.ovh.net
  base                                                     | 3.7 kB     00:00
  extras                                                   | 3.4 kB     00:00
  extras/primary_db                                        |  31 kB     00:00
  local-centos6-x86_64-x86_64                              | 4.0 kB     00:00
  updates                                                  | 3.4 kB     00:00
  updates/primary_db                                       | 3.3 MB     00:00
  Resolving Dependencies
  There are unfinished transactions remaining. You might consider running yum-complete-transaction first to finish them.
  The program yum-complete-transaction is found in the yum-utils package.
  --> Running transaction check
  ---> Package man-pages.noarch 0:3.22-20.el6 will be installed
  --> Finished Dependency Resolution

Dependencies Resolved

# 

#  Package            Arch            Version                 Repository     Size

Installing:
 man-pages          noarch          3.22-20.el6             base          4.8 M

# Transaction Summary

Install       1 Package(s)

Total download size: 4.8 M
Installed size: 4.3 M
Is this ok [y/N]: y
Downloading Packages:
man-pages-3.22-20.el6.noarch.rpm                         | 4.8 MB     00:01
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : man-pages-3.22-20.el6.noarch                                 1/1
  Verifying  : man-pages-3.22-20.el6.noarch                                 1/1

Installed:
  man-pages.noarch 0:3.22-20.el6

Complete!

[root@dev02 ~]# man qsub
QSUB(1P)                   POSIX Programmer’s Manual                  QSUB(1P)

PROLOG
       This  manual  page is part of the POSIX Programmer’s Manual.  The Linux
       implementation of this interface may differ (consult the  corresponding
       Linux  manual page for details of Linux behavior), or the interface may
       not be implemented on Linux.

NAME
       qsub - submit a script

SYNOPSIS
       qsub [-a date_time][-A account_string][-c interval]
                [-C   directive_prefix][-e   path_name][-h][-j   join_list][-k
       keep_list]
               [-m mail_options][-M mail_list][-N name]
               [-o path_name][-p priority][-q destination][-r y|n]
               [-S path_name_list][-u user_list][-v variable_list][-V]
               [-z][script]

DESCRIPTION
       To  submit  a script is to create a batch job that executes the script.
       A script is submitted by a request to a batch server.
