### ISSUE TITLE
/KIMEL is not mounted on dev*, compute or mgmt1 nodes

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#33]
Title says it all. 

``` sh
[jpipitone@login ~]$ mount | grep KIMEL
mgmt1:/core/KIMEL on /KIMEL type nfs4 (rw,intr,addr=10.2.1.121,clientaddr=10.2.1.122)
[jpipitone@login ~]$ ssh dev01 mount | grep KIMEL
[jpipitone@login ~]$
```

Also the mount on `mgmt1` is under `/export` only, and not `bind` mounted to `/KIMEL`.

**Comment by djrotenberg** [comment]
Is this a requirement? If so it's not a problem to have this mounted on these machines. 

Are you looking for these to be available on each of the dev, compute and mgmt machines?

**Comment by pipitone** [comment]
> Is this a requirement? 

It'd certainly be handy. And not just for /KIMEL, but the other storage
arrays also, I imagine. ro is fine, and I think what we discussed before.  

> Are you looking for these to be available on each of the dev, compute and mgmt machines?

Yup.

**Comment by djrotenberg** [comment]
The mount from mgmt1 has been applied to node01-node22:
mgmt1:/core/KIMEL                     /KIMEL                  nfs4  rw,defaults,sync,tcp,timeo=600,retrans=2,rsize=32768,wsize=32768,intr,noatime       0  0
