### ISSUE TITLE
Wiki should say that logs won't be delivered unless user has self-authorized ssh keys

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#34]
I was trying to figure out why logs for my jobs weren't appearing in the folder I specifically requested (using `qsub -o logs/`) and so started reading up on PBS/Torque troubleshooting here: 
http://www.cslu.ogi.edu/~zak/debianclusters/Troubleshooting_Torque_and_Maui

Sure enough, my logs were staying in the `nodeXX:/var/spool/torque/undelivered` folder, and this is because I hadn't put my own `~/.ssh/id_rsa.pub` key into `~/.ssh/authorized_keys`.  (To be honest, I actually thought I _had_ because I was able to passwordlessly ssh to `dev01`.) Once I had updated my `authorized_keys` file, I started to receiving logs. 

So, either: 
1. Update the SCC wiki to let people know they need to do this... and perhaps even throw up a warning if they attempt to submit jobs and haven't done this. :-)
2. Update the SCC ssh rules so that passwordless SSH access is allowed between nodes automatically. 

I vote for #2, actually, since now we have [`reaver` set up](https://github.com/CAMH-Scientific-Computing/SCC/issues/26#issuecomment-112119052) we can actually open up access without really worrying too much about people shelling into nodes they aren't running jobs on.

**Comment by djrotenberg** [comment]
Another solution is to add a line adding the key to the user's authorized keys file to the automated ssh setup scripts upon user creation. A note on the wiki would certainly be helpful.

**Comment by djrotenberg** [comment]
Just a note that the user-setup scripts now include a line to add the `id_rsa.pub` key into the user's `authorized_keys` file.

**Comment by andycamh** [comment]
better add following in .ssh/config
Host *
StrictHostKeyChecking no
