### ISSUE TITLE
What is /quarantine/Libs/lib64? 

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#35]
This is automatically put in my `LD_LIBRARY_PATH`, but it looks like it's got a whole pile of stuff going on in there. It has minc libraries, X libraries, python, qt, etc... 

What exactly is in there and what depends on it? 

We should probably move to organizing libraries into the quarantine modules that depend on them.

**Comment by andycamh** [comment]
delete this line from /etc/profile.d/module.sh
