### ISSUE TITLE
node time is not syncronized

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#36]
We had something like this before with NTP not running (see #5) but currently the time is up to an hour off on some of the nodes:

``` sh
[jpipitone@dev01 ~]$ date; for i in node{01..22}; do echo $i $(ssh $i date)& done 2>&1 | grep node                                                           
Sun Jun 21 13:20:07 EDT 2015
node05 Sun Jun 21 12:59:48 EDT 2015
node07 Sun Jun 21 13:06:19 EDT 2015
node10 Sun Jun 21 13:29:55 EDT 2015
node09 Sun Jun 21 12:41:24 EDT 2015
node13 Sun Jun 21 12:43:11 EDT 2015
node14 Sun Jun 21 12:59:23 EDT 2015
node15 Sun Jun 21 12:38:35 EDT 2015
node01 Sun Jun 21 13:20:07 EDT 2015
node19 Sun Jun 21 13:04:53 EDT 2015
node12 Sun Jun 21 13:31:23 EDT 2015
node11 Sun Jun 21 13:54:05 EDT 2015
node20 Sun Jun 21 12:49:48 EDT 2015
node17 Sun Jun 21 13:08:58 EDT 2015
node16 Sun Jun 21 12:54:30 EDT 2015
node02 Sun Jun 21 13:34:18 EDT 2015
node21 Sun Jun 21 12:43:09 EDT 2015
node22 Sun Jun 21 12:21:14 EDT 2015
node06 Sun Jun 21 13:36:31 EDT 2015
node04
node03
node08
node18
```

**Comment by pipitone** [comment]
Okay, well, since this was starting to cause me lots of problems, I just ran `ntpdate -u mgmt2` on all of the nodes to force a time update. 

I noticed also that the `ntpd` service isn't running on any of the nodes, so I ran `chkconfig ntpd on` to start the service on boot, as well as `chkconfig ntpdate on` to reset the clock on boot.

[Keeping time is difficult.](http://rachelbythebay.com/w/2014/06/14/time/)

**Comment by andycamh** [comment]
update all nodes config to direct ntp server to mgmt2, mgmt1, inner nodes seems cannot get out.
It sound work now.
I will check it later.

**Comment by djrotenberg** [comment]
Could we please confirm and close.

**Comment by andycamh** [comment]
It have been solved.
