### ISSUE TITLE
Reaver kills my jobs every hour

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#37]
So here's something: [reaver](https://github.com/Norky/PBS-tools/blob/master/sbin/reaver) is killing my jobs everytime it runs, and this means I can't really use the SCC. :-)

I've tracked down why. The problem is with [line 163](https://github.com/Norky/PBS-tools/blob/master/sbin/reaver#L163):

``` perl
open(PS,"ps -A -o pid,state,uid,user,command |");
```

According to the `ps` man page: 

> If the length of the username is greater than the length of the display column, the numeric user ID is displayed instead.

What's happening is that `reaver` is requesting a list of processes and expecting to get the username for each process, but when users have a username greater than 8 characters, the UID is displayed instead. These don't match against the username, and so reaver assumes they aren't owned by the user, and kills them. 

The solution is to edit line 163 to explicitly request that the user column is "wide" (i.e. will widen automatically), like so: 

``` perl
open(PS,"ps -A -o pid,state,uid,user=WIDE-USER-COLUMN,command |");
```

**Comment by pipitone** [comment]
I've created a pull request against reaver so that this change will be included: https://github.com/Norky/PBS-tools/pull/1

**Comment by pipitone** [comment]
Okay, I've also updated the `reaver` script on all of the nodes. :-)

There must be a fancy way of doing this, but I just used a for loop and `scp`. Perhaps sometime you can show me how you do configuration management.

**Comment by djrotenberg** [comment]
That's great. I would recommend parallel scp, "pscp" e.g.

pscp file node01-node22:/location/
