### ISSUE TITLE
Explore other job scheduling policies

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#39]
At the moment the number of jobs a single user can have running is limited to, I believe, 8. This means that if there is only a few users active, the SCC is massively underused. Case in point, this weekend I've been the only one using the cluster, but I've been 1/3 as productive as I could have been had I been able to fully use all of the nodes. However, there's a problem with simply allowing everyone to have as many jobs run as they'd like, since this might end up with one user hogging the system for days. 

I'm opening this ticket as a point of discussion and exploration into alternative scheduling policy options we could employ to make more use of the cluster resources whilst still maintaining fair usage. 

Some ideas of things we could consider (sorry, can't link to the Adaptive Computing documentation because the site is currently down): 
- hard/soft limits for jobs/resources/walltime, 
- preemption policies to allow some jobs to be stopped/suspended/requeued if another user's jobs are waiting
- multiple subordinate queues for different job lengths e.g. `short.q` for jobs 8< hours (all nodes can be used), `medium.q` for jobs 8-24 hours (75% of nodes can be used), and `long.q` for jobs >24 hours (50% of nodes can be used).

**Comment by pipitone** [comment]
Okay, I think the last option (multiple queues) could actually work if we set up a so-called [routing queue](http://docs.adaptivecomputing.com/torque/archive/3-0-2/4.1queueconfig.php#routing).

In the example they show setting up a default queue that routes jobs to queues that each have different restrictions. So for example, we could have this configuration (obviously untested, but for illustrative purposes): 

``` sh
# routing queue
create queue route
set queue route queue_type = Route
set queue route route_destinations = long
set queue route route_destinations += medium
set queue route route_destinations += short
set queue route enabled = True
set queue route started = True

# A queue for jobs less than 8 hours
create queue short
set queue short queue_type = Execution
set queue short resources_max.walltime = 8:00:00
set queue short resources_default.walltime = 1:00:00
set queue short enabled = True
set queue short started = True

# A queue for jobs between 8-24 hours
create queue medium
set queue medium queue_type = Execution
set queue medium resources_min.walltime = 8:00:01
set queue medium resources_max.walltime = 24:00:00
set queue medium resources_default.walltime = 12:00:00
set queue medium max_user_run = 15
set queue medium enabled = True
set queue medium started = True

# A queue for jobs greater than 24 hours
create queue long
set queue long queue_type = Execution
set queue long resources_min.walltime = 24:00:01
set queue long max_user_run = 10
set queue long enabled = True
set queue long started = True

# have all jobs go through the routing queue
set server default_queue = batch
set server resources_default.walltime = 1:00:00
```

From my understanding, this would enable a single user to completely use the SCC, but at any point in time, only 10 of their jobs could be jobs that run for more than 24 hours, and only 15 that run for 8-24 hours. They could therefore have all nodes occupied, but at most for 24 hours before 10 were freed up for others to use (say, if they submitted ten 24h+ jobs and ten 24h jobs). 

This isn't as slick as using preemption or some sort of rolling usage-based policy (for instance, Maui's [fairshare](http://docs.adaptivecomputing.com/maui/6.3fairshare.php) scheduling, of course.

**Comment by djrotenberg** [comment]
The above solution would work reasonably well. However, since Maui is already a component of the system, I have revised the maui.cfg file with relevant fairshare parameters, and enabled this in torque's sched_config. On this note I have also increased the number of jobs that can be run at max to 20 (likely this will be increased further).

**Comment by pipitone** [comment]
Great. Let's see how it goes.
