### ISSUE TITLE
Added CIVET/1.1.12 to /quarantine

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#40]
I've installed CIVET/1.1.12 into /quarantine. I spoke with Mallar and he confirmed that we're allowed to share CIVET. The caveat is that if CIVET is used, authorship must be negotiated with Mallar and Jason (from MICe). I'm not sure how we want to enforce/encourage this. I imagine this won't be the first time software with restrictions will be needed on the SCC. 

Thoughts?

**Comment by djrotenberg** [comment]
We could create a new user group, only whose members may access CIVET. These users would only be added to the group after an agreement has been established between themselves, Mallar and Jason.

**Comment by andycamh** [comment]
1. create a group CIVET
2. change /quarantine/CIVET and subdir with group owner CIVET
3. disable other user permission on /quarantine/CIVET/1.1.2
4. add pipitone ,david and me to group to CIVET
