### ISSUE TITLE
On mgmt2 /usr/local/lib/libz.so points to /usr/local/lib/libz.so

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#43]
> "Something strange is afoot at the Circle K" 
>  -- Ted (Bill and Ted's Excellent Adventure)

**Comment by djrotenberg** [comment]
As soon as I add Andy to this group, we'll take a look.

**Comment by andycamh** [comment]
There is a file in /usr/lib/libz.so
rpm -qf  /usr/lib/libz.so 
file /usr/lib/libz.so is not owned by any package
So I guess it maybe compiling something need to find libz.so in /usr/lib or /usr/local/lib
and 
ls -l /usr/lib/libz.so 
lrwxrwxrwx 1 root root 18 Sep 19  2014 /usr/lib/libz.so -> /usr/lib64/libz.so
