### ISSUE TITLE
/quarantine/Libs/lib64 considered dangerous

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#46]
I don't think issue #35 is benign, and it needs to be fixed. The problem is that this folder of assorted libraries on the default `LD_LIBRARY_PATH` is messing with using system-wide software (in my case, xsltproc): 

``` sh
[jpipitone@mgmt2 jvarkit]$ xsltproc 
xsltproc: relocation error: xsltproc: symbol xsltMaxVars, version LIBXML2_1.0.24 not defined in file libxslt.so.1 with link time reference
[jpipitone@mgmt2 jvarkit]$ which xsltproc
/bin/xsltproc
[jpipitone@mgmt2 jvarkit]$ echo $LD_LIBRARY_PATH
/quarantine/JAVA/1.7.0/lib:/quarantine/Libs/lib64/:/quarantine/Libs/lib64/:/quarantine/Libs/lib64/
[jpipitone@mgmt2 jvarkit]$ export LD_LIBRARY_PATH=/quarantine/JAVA/1.7.0/lib
[jpipitone@mgmt2 jvarkit]$ xsltproc 
Usage: xsltproc [options] stylesheet file [file ...]
   Options:
    --version or -V: show the version of libxml and libxslt used
    --verbose or -v: show logs of what's happening
    --output file or -o file: save to a given file
    --timing: display the time used
   ... 
```

**Comment by djrotenberg** [comment]
This was removed from the modules.sh file, and should no longer appear.

**Comment by pipitone** [comment]
Are you sure that's an okay thing to do? Wouldn't some of the quarantined modules depend on that mess?

It might be possible to determine this by doing something ugly like: 

``` sh
for module in <list of modules>
do 
    module load $module
    find /modulepath/ -executable -exec ldd {} \; | grep "not found"
    module purge
done
```

If anything unresolved is turned up, then we'd know there are libraries to resolve for that module.

'course, just because something _can_ link, doesn't mean it will work when it does (given a version conflict), but it's a start.
