### ISSUE TITLE
JAVA/1.7.0 doesn't have javac

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#47]
I think the JAVA/1.7.0 module may only be the JRE, but should probably be the entire JDK so that we can compile java bytecode: 

http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html

**Comment by djrotenberg** [comment]
You're correct. This was due to the requirement for a particular project at the time. 

Andy -  please create a new module that includes the entire JDK.

**Comment by pipitone** [comment]
I have the 1.7.0 JDK tarball downloaded here: 
    /imaging/home/kimel/jpipitone/software/jdk-7u80-linux-x64.tar.gz

**Comment by andycamh** [comment]
Thanks!
I will add it to module.

Andy Wang
Research Methods Specialist, Scientific Computing
Centre for Addiction and Mental Health (CAMH)
T: 416 535 8501 x36482
andy.wang@camh.ca

**Comment by andycamh** [comment]
The system already have JDK module.

module add JAVA/1.7.0

java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode

Andy Wang
Research Methods Specialist, Scientific Computing
Centre for Addiction and Mental Health (CAMH)
T: 416 535 8501 x36482
andy.wang@camh.ca

---

From: Andy Wang
Sent: Thursday, September 03, 2015 9:25 AM
To: CAMH-Scientific-Computing/SCC; CAMH-Scientific-Computing/SCC
Subject: RE: [SCC] JAVA/1.7.0 doesn't have javac (#47)

Thanks!
I will add it to module.

Andy Wang
Research Methods Specialist, Scientific Computing
Centre for Addiction and Mental Health (CAMH)
T: 416 535 8501 x36482
andy.wang@camh.ca

**Comment by pipitone** [comment]
Nope, that's the JRE not the JDK. :-)

**Comment by andycamh** [comment]
replace with jdk_1.7.0_80

Andy Wang
Research Methods Specialist, Scientific Computing
Centre for Addiction and Mental Health (CAMH)
T: 416 535 8501 x36482
andy.wang@camh.ca
