### ISSUE TITLE
SSH from dev02 to dev01 results in error

### ISSUE THREAD

**Issue by djrotenberg** [CAMH-Scientific-Computing/SCC#49]
Navigation between the development nodes is impaired:

[root@dev02 ~]# ssh dev01
ssh: /quarantine/Libs/lib64/libcrypto.so.10: no version information available (required by ssh)
ssh: /quarantine/Libs/lib64/libcrypto.so.10: no version information available (required by ssh)
ssh: /quarantine/Libs/lib64/libcrypto.so.10: no version information available (required by ssh)
ssh: relocation error: ssh: symbol EC_GROUP_cmp, version OPENSSL_1.0.1_EC not defined in file libcrypto.so.10 with link time reference

**Comment by pipitone** [comment]
See #26, apparently this is on purpose. :-)

But honestly, this is a problem with `/quarantine/Libs` again (#46, #35). If you remove that from your `LD_LIBRARY_PATH`, you shouldn't have any trouble SSHing around.

**Comment by andycamh** [comment]
comment out .bash_profile off 
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/quarantine/Libs/lib64

test ok!

**Comment by djrotenberg** [comment]
Perfect, thanks Andy!
