### ISSUE TITLE
Detect nodes that are 'eating' jobs and automatically disable. 

### ISSUE THREAD

**Issue by djrotenberg** [CAMH-Scientific-Computing/SCC#57]
This behavior has occurred across clusters, and can be a serious problem. If a node is having an issue, jobs will almost immediately fail, resulting in a cascade of failed jobs. 

If we can detect this behavior and disable the node(s) in the queue (along with a message identifying the node) we can safely diagnose without having more jobs failing in the mean time. 

Recommend instituting the following scripts:

http://docs.adaptivecomputing.com/torque/archive/3-0-2/a.cmomconfig.php
http://docs.adaptivecomputing.com/torque/archive/3-0-2/11.2healthcheck.php

**Comment by andycamh** [comment]
change config to let when cpu load over 12 the compute node will refuse to accept new job ,
only when cpu load  drop under 6 it will accept new job again
