### ISSUE TITLE
ssh doesn't work from the dev nodes

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#63]
Perhaps this is by design, but it's quite annoying not to be able to `ssh` or use git over ssh on the development nodes: 

``` sh
[jpipitone@dev02 ~]$ /usr/bin/ssh login.scinet.utoronto.ca
ssh: connect to host login.scinet.utoronto.ca port 22: Network is unreachable
```

**Comment by andycamh** [comment]
we just have two outside connecting, one is used for ftp and the other used for login.
So better we should apply for more ip to deal with this problem

**Comment by andycamh** [comment]
currently use login01 as nat server, should work now.
