### ISSUE TITLE
'debug' queue uses dev02

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#66]
I just tried scheduling a job to the `debug` queue and the job ended up running on node `dev02`, which I don't think is what you want, since users may be working on dev02. 

Just thinking: perhaps only one development node is necessary given the use these days. `dev02` could be scratched, and `node02` used only for debug (or very short jobs, <1hr)?

**Comment by andycamh** [comment]
I am planning to upgrade one of dev02 to centos 6.7 because some of the node is centos 6.7 now.
dev01 and dev02 did not have infiniband, so better to leave one as debug node
