### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by andycamh** [CAMH-Scientific-Computing/SCC#70]
[sganeshan@node21 ~]$ ./test.sh
./test.sh: line 7: module: command not found

**Comment by andycamh** [comment]
Solution: 
1. module in bash use function, when submit with #!/bash -l , it will execute correctly
2. upgrade module to 3.2.10 and add bash_completion function, sound solve the problem
3. added support for  csh and tcsh

**Comment by pipitone** [comment]
> 1. module in bash use function, when submit with #!/bash -l , it will execute correctly

Yeah, this is because only login bash shells read /etc/profile. You can
also just ask people to put `source /etc/profile` in their scripts if
they don't want to run a login shell.
