### ISSUE TITLE
Install fail2ban and/or another intrusion detection system

### ISSUE THREAD

**Issue by pipitone** [CAMH-Scientific-Computing/SCC#8]
Given that we do allow outside access to the SCC (from SciNet currently), and also from the CAMH network (which is unrestricted) we should probably have something in place to stop malicious access attempts. I suggest, atleast fail2ban since it's easy to set up and works well enough. Digital Ocean has put together a nice tutorial on setting it up for CentOS 6: 
     https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-centos-6

**Comment by djrotenberg** [comment]
Thanks Jon. We've been using the OSSEC host intrusion detection software.

**Comment by djrotenberg** [comment]
I've installed fail2ban as well with default configuration for the time being.

**Comment by djrotenberg** [comment]
Fail2ban has also been installed on mgmt1.
